#!/usr/bin/env python3
"""Build script: embed public/ files into src/static.ts for esbuild bundling."""
import os, sys

def escape_ts(s):
    """Escape content for TypeScript template literals."""
    s = s.replace('\\', '\\\\')
    s = s.replace('`', '\\`')
    s = s.replace('${', '\\${')
    return s

MIME_MAP = {
    '.html': 'text/html; charset=utf-8',
    '.css':  'text/css; charset=utf-8',
    '.js':   'application/javascript; charset=utf-8',
    '.json': 'application/json',
    '.svg':  'image/svg+xml',
    '.png':  'image/png',
    '.ico':  'image/x-icon',
}

os.chdir(os.path.dirname(os.path.abspath(__file__)))

lines = [
    '// Auto-generated by build.py — do not edit directly',
    '',
    'export const STATIC_FILES: Record<string, { content: string; mime: string }> = {',
]

public_dir = 'public'
for fname in sorted(os.listdir(public_dir)):
    fpath = os.path.join(public_dir, fname)
    if not os.path.isfile(fpath):
        continue
    ext = os.path.splitext(fname)[1]
    mime = MIME_MAP.get(ext, 'text/plain; charset=utf-8')
    
    with open(fpath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    escaped = escape_ts(content)
    url_path = '/' + fname
    lines.append(f"  '{url_path}': {{ content: `{escaped}`, mime: '{mime}' }},")

lines.append('}')

os.makedirs('src', exist_ok=True)
with open('src/static.ts', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print(f"Generated src/static.ts ({len(os.listdir(public_dir))} files)")

# Build with esbuild
ret = os.system('npx esbuild _worker.ts --bundle --outfile=_worker.js --format=esm --external:__STATIC_CONTENT_MANIFEST --platform=browser 2>&1')
if ret != 0:
    print("esbuild failed!")
    sys.exit(1)

size = os.path.getsize('_worker.js')
print(f"Build complete: {size} bytes ({size/1024:.1f} KB)")
