# Cloudflare Pages configuration (Advanced Mode)
name = "sribuu"
compatibility_date = "2024-07-06"

# D1 Database
[[d1_databases]]
binding = "sribuu_db"
database_name = "sribuu-db"
database_id = "ac305b13-ae55-45ca-95a9-ca25424e98e7"
migrations_dir = "migrations"
