# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# sys.path prepend for the application
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
timezone = Asia/Jakarta

# template used to generate migration file names; default uses date/time
# file_template = %%(rev)s_%%(slug)s

# max length of characters to apply to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during the "revision" command
# regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file in the versions directory
# sourceless = false

# version location specification; defaults to `migrations/versions`
# version_locations = %(here)s/bar %(here)s/bat migrations/versions

# output encoding used for revision files
output_encoding = utf-8

# the output encoding to use when Alembic writes the script.py
# script_location = migrations
# script_location = %%(here)s/migrations

sqlalchemy.url = driver://user:pass@localhost/dbname


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for
# the full list of options.
#
# Uncomment to enable ruff formatting on generated migration scripts:
# hooks = ruff
# ruff.type = exec
# ruff.executable = ruff
# ruff.options = check --fix REVISION_SCRIPT_FILENAME

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
